### ISSUE TITLE
Autostart on android 

### ISSUE THREAD

**Issue by tarbib** [mycelium-com/wallet-android#432] opened 2017-11-29 05:19 UTC
![Uploading WeChat Image_20171129131625.png…]()

![wechat image_20171129131620](https://user-images.githubusercontent.com/2255433/33359103-de49f3a0-d507-11e7-9281-a4404c2ae05a.png)

Hello

Any reasons why my mycelium wallet does not notify me when I have trade offer ?

The app has the permission to autostart. I missed many trades liek this... The only way I have is to open the app go to Buy sell function.

Thanks

Thomas

**Comment by Drankking** [comment] 2017-11-30 21:01
Mute the thread

**Comment by Giszmo** [comment] 2017-12-06 20:09
I'm afraid this is a duplicate of #77. Our team is growing and once we have modularization released, we hopefully get to fix all the bugs.

**Closed by Giszmo** 2017-12-06 20:09 UTC
Labels: bug, duplicate
