### ISSUE TITLE
Transaction detail shows incorrect block number and number of confirmations

### ISSUE THREAD

**Issue by utaxiu** [mycelium-com/wallet-android#536] opened 2019-12-24 09:37 UTC
Hello,
today I noticed that when I open transaction details in Mycelium it shows incorrect block number and number of confirmations. It is visible in the attachment.

_Tx detail in Mycelium:_
![wallet](https://user-images.githubusercontent.com/49832383/71406466-98b14580-2638-11ea-89f3-1ade1c39d149.png)
_Tx detail in blockexplorer:_
![blockexplorer](https://user-images.githubusercontent.com/49832383/71406475-9f3fbd00-2638-11ea-9214-6017894b23b9.png)

**Comment by EAWF** [comment] 2019-12-24 15:34
I have the same issues, which have been lingering on for a while now. It seems to be a lack of attention to the programming regarding the block explorers. I've found it's just easier to cut and paste the transaction hash or the address you want to locate into your favorite working block explorer, where you can depend on the data being correct.

**Comment by Giszmo** [comment] 2019-12-27 08:48
Yes, this is a duplicate of #503 

The copy-paste part should not be necessary, as you can configure any of several block explorers to open when clicking on an address or tx hash in the details screen.

**Closed by Giszmo** 2019-12-27 08:48 UTC
