### ISSUE TITLE
The transaction was rejected by the network. This indicates that your wallet is out of sync

### ISSUE THREAD

**Issue by cadbitcoininvestor** [mycelium-com/wallet-android#463] opened 2018-05-15 15:44 UTC
I have started getting this error message over the past few days anytime I try to send a transaction with Mycelium. Sometimes the transactions go though many hours after I see the message and sometimes they do not go though at all.

I have tested with a fresh install of the app, 2 WIFI and 1 mobile networks.

I have also verified that the accounts are synced by clicking on account 3 dots then Reload account.

I get this message when trying to spend from cold storage and when trying to spend from a Trezor. I select Max fee and Max amount to ensure it is not a transaction fee issue.

**Comment by sergeylappo** [comment] 2018-05-15 15:52
Hello,
Thank you for the information.
We are already working on resolving this issue.

**Comment by cadbitcoininvestor** [comment] 2018-05-16 06:53
Update: This transaction actually went though several hours later despite the error message:

[E] Server connection failed with error: 99.

How does this happen that the transaction fails at the time it is created and sometimes goes though a few hours later? Is there a corresponding server log that can be analyzed when the client logs these server connection failed error 99 events?

Also the issue has been tagged with can't reproduce however there are other users reporting seeing the same issue on bitcointalk in this thread: https://bitcointalk.org/index.php?topic=3800338.0

**Comment by Giszmo** [comment] 2018-05-18 05:12
We are fully dedicated to this issue since more than 24h with high reproducibility. Unfortunately I personally could not reproduce it when I had monitoring setup but I had it happen, too. Now we study code, debug servers, add logging, review what we have changed ...

**Comment by cadbitcoininvestor** [comment] 2018-05-27 10:56
Has there been any development on this issue? Is it save to use my Trezor again with Mycellium?

**Comment by sergeylappo** [comment] 2018-05-28 17:48
@cadbitcoininvestor, yes it works now. Would close. Please feel free to reopen If problem persists for you.

**Closed by sergeylappo** 2018-05-28 17:48 UTC
Labels: bug

**Comment by jandresboston** [comment] 2019-04-01 02:52
I have sent many support tickets to Mycelium and have received no response for weeks. I am getting a transaction signing error while still being charged the transaction/mining fee. Happened with all levels pricing fees. Attached is the raw transaction data that Mycelium instructed me to send to technical support. This is all quite disconcerting. I would attach a screenshot but I can't here. Please help.

01000000016e86516f2d8016974d538c73813627fc081dd58abbc47d08b66a6ee4410b7d86030000006a473044022040005534717b66ee604989913518d6e942b75396b019bf05c5ae490a44ff1d8c02201b17b69c7c899aa065fe97e352919b3e4ae26cbb0ad2b8d02d20f681c8bc7e73012102835b34cbdde64c11f2a2c48c14ccc54ef30a7c8393f3cf59a7d510821a9a2eabffffffff028a182c04000000001976a914644765a9ea54508b70f96b9bca893b54a2d9e4a088ac470f5b01000000001976a9146d35102b37fdb3440f64b25dc969a5e3fe7eccfa88ac00000000

**Comment by Bruno-engeletricista** [comment] 2021-04-07 20:00
When sending, displays the following message:
transaction signing failed. please report this incident to tech support. Raw transaction was copied to cliboard, if possible please attach if to your request
