### ISSUE TITLE
Order or transaction in same block are unsorted. Lots of confusion.

### ISSUE THREAD

**Issue by Transisto** [mycelium-com/wallet-android#198] opened 2015-10-03 07:23 UTC
When many transaction are done around the same time, the transaction within the same block are either completely unsorted or sorted inversely to way transaction are supposed be ordered.

This cause a lot of accounting confusion.

Please use time or broadcasting for at least sorting out outgoing transactions.

**Comment by Giszmo** [comment] 2015-12-18 16:47
The transaction history is sorted by confirmation time and ordering in the block, not by first seen time. You suggest to change that?

The blockchain is a timestamping tool and the closest to definite truth that one can get on the ordering of events (transactions). I can see how an accounted might want to trust his phone's watch more than the blockchain but I guess this issue might only get addressed in a follow-up project that we are working on. @DanielWeigl? Close?

**Comment by Transisto** [comment] 2015-12-21 00:46
What does that mean ordering in the block ?  I send 3 transaction 3 minute appart and they show up in the wrong order how does that make any sense ?

**Comment by Giszmo** [comment] 2015-12-21 01:20
The ordering by block height and transaction order inside the block is wallet agnostic. If the sending wallet picked a different ordering it would be arbitrary from an outside perspective.

**Comment by Transisto** [comment] 2015-12-21 01:58
I'm talking about myself doing outgoing transaction on same wallet.   For example, sending 2 BTC, then 0.3 btc then 0.2 btc  wallet will show sending 2 BTC as last transaction sent,I'd then freak out that we made the mistake of sending 2btc instead of 0.2

**Comment by Giszmo** [comment] 2015-12-21 16:38
It's a very common thing that transactions don't confirm in the order they were made if you don't pay high fees and even if you do, some transactions may confirm out of order or not at all, requiring to re-do the transaction. On top of that, the transaction might run victim of a malleability attack replacing it by a functionally equal transaction that double-spends against the one you wanted to see there in your transaction history. From a "who gets how many bitcoins" perspective, these things are all nice but I do understand that an accountant used to a bank interface might get anxious with how bitcoin works.

Even if we fixed this issue in a way that used the local timestamp for the local history, this would result in the history looking different across devices unless we synchronized these timestamps but at least across bip44 wallets this would be close to impossible to standardize with all the privacy concerns involved.

I tend to close this as "won't fix" for all the reasons stated above.

**Comment by fortran77** [comment] 2016-04-20 03:49
I too have experienced some confusion when sends confirmed not in the order initiated. Any fix would require the wallet to store a timestamp for when the user initiated a send.

If the wallet can be made to store these timestamps at all, then there are two obvious aproaches to using these timestamps.

The high-overhead approach: Allow sorting on desired values, e.g., initiation time or confirmation time.

The low-overhead approach: Add a symbol (e.g., *) to show wherever confirmation order differs from initiation order.

**Comment by Giszmo** [comment] 2019-07-24 00:43
Bitcoin is a timestamping system and the order of confirmed transactions is very relevant and well defined. As said above, I'll close this for now as won't fix.

**Closed by Giszmo** 2019-07-24 00:43 UTC
Labels: enhancement, wontfix
