### ISSUE TITLE
Fiat balance stuck in USD in the Accounts and Transactions tabs

### ISSUE THREAD

**Issue by ghost** [mycelium-com/wallet-android#383] opened 2017-08-31 18:38 UTC
I have my local currency set to Canadian Dollars (CAD). However, the balances shown in the Accounts and Transactions tabs are in USD while the balance in the Balance tab is displayed correctly in CAD.

![screenshot_20170831-131555](https://user-images.githubusercontent.com/28612913/29939208-19faaa34-8e59-11e7-8ef8-f3ca7e8e97d6.png)
![screenshot_20170831-131559](https://user-images.githubusercontent.com/28612913/29939209-19fb975a-8e59-11e7-8626-9add5c5ed570.png)
![screenshot_20170831-131620](https://user-images.githubusercontent.com/28612913/29939207-19f9d2b2-8e59-11e7-805b-220c891bf3d1.png)

**Comment by Giszmo** [comment] 2017-09-08 01:02
Thanks for reporting. so did you ever switch around currencies? I see you have only CAD selected? Can't reproduce your issue.

**Comment by Giszmo** [comment] 2017-10-18 21:23
Please try changing the exchange rate provider and the currency and report back how that went.

**Comment by the9ull** [comment] 2017-10-23 10:30
I have this problem too. EUR is my currency and I use the Kraken exchange rate. I changed it to Bitstamp but the USD is still there

**Comment by sergeylappo** [comment] 2018-02-23 07:08
@ghost, @the9ull please try our new testnet release and check if bug is still there.

**Comment by sergeylappo** [comment] 2018-07-31 13:06
Closing as no respond for 5 months

**Closed by sergeylappo** 2018-07-31 13:06 UTC
Labels: bug, can't reproduce
