### ISSUE TITLE
Issue with disappearing balance and tx history. (similar to #490)

### ISSUE THREAD

**Issue by ashipka11** [mycelium-com/wallet-android#507] opened 2019-04-22 19:04 UTC
Greetings, Mycelium team!

I really like the application and am using it for a long time. but today I updated application to its latest version and what happens after. My single address, which previously was normally receiving transactions sent to "1" and to "3" (coz Mycelium client converts keys to all formats in previous one update). also it displayed to me total balance on both (1 and 3) addresses. But with new update everything except "1" gone and firstly I didnt see only transactions (they appear like zeroes), and after I re-synced account (that address) balance went to zero (coz coins actually are on "3" address not on "1" which is displayed).
After many tries and attempts I ask you to help me.
I tried to downgrade to previous version, but it didn't work. later I updated it again from Google play. and again : client closes right on the first screen with logo and name. I cant even enter in any version of client.

Knowing that coins are in my device I didn't tried to remove it completely with re-installing back, because I am afraid of necessary data loss.

Best regards,
DecardCoin

**Comment by ashipka11** [comment] 2019-04-22 19:11
prev. version 2.11.1.20 - all works wonderful

new version 2.11.1.26 - stucked with formats

**Comment by ashipka11** [comment] 2019-04-22 19:15
and this [screenshot ](https://telegra.ph/Mycelium-scr-04-22) to show you how it start looks like after update

**Comment by Giszmo** [comment] 2019-06-06 05:25
This is a duplicate of #508 and meanwhile fixed.

**Closed by Giszmo** 2019-06-06 05:25 UTC
